---
stages:
  - deploy


deploy:
  stage: deploy
  tags:
    - shiny
  before_script:
    - hostname
    - sudo mkdir -p /srv/shiny-server/MVApp
  script:
    - sudo cp -rf * /srv/shiny-server/MVApp/
    - sudo chown -R shiny:shiny /srv/shiny-server/MVApp/
