---
stages:
  - deploy


deploy:
  stage: deploy
  image: ubuntu:latest
  tags:
    - cthciadm
  before_script:
    - hostname
    - sudo mkdir -p /srv/shiny-server/MVApp
  scripts:
    - sudo cp -rf * /srv/shiny-server/MVApp/
