---
version: '3.7'
services:
  shiny:
    build:
      context: .
    image: mvapp:latest
    container_name: mvapp
    restart: always
    volumes:
      - ./logs:/var/log
    ports:
      - "80:80"
