## libraries are installed in the Dockerfile ##
###############################################

# Load all the libraries 
library("shiny")
library("shinythemes")
library("plotly")
library("doBy")
library("reshape")
library("plotrix")
library("corrplot")
library("tidyverse")
library("reshape2")
library("FactoMineR")
library("devtools")
library("factoextra")
library("missMDA")
library("dplyr")
library("DT")
library("RColorBrewer")
library("multcomp")
library("colorRamps")
library("gplots")
library("multcompView")
library("data.table")
library("splines")
library("agricolae") #for HSD.test for Tukey in case we want to use it
library("wesanderson") #for nice palette colors 
library("car")
library("Hmisc")
library("splitstackshape")
library("HH")
library("lme4")
library("MASS")
library("ggpubr")
library("magrittr")
library("ggrepel")
library("pvclust")
library("NbClust")
library("quantreg")
library("ggbeeswarm")
library("ggridges")
library("cowplot")
library("forcats")
library("gapminder")
